This file tests visualization and data manipulation for use in a dashboard

In [1]:
# Import dependencies
import os
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# import data - sessions of congress
sessions_df = pd.read_csv("..\\data\\external\\sessions.csv")
sessions_df.head()

   Congress  Start_Date    End_Date
0         1  1789-03-04  1791-03-03
1         2  1791-03-04  1793-03-03
2         3  1793-03-04  1795-03-03
3         4  1795-03-04  1797-03-03
4         5  1797-03-04  1799-03-03

In [4]:
# convert start_date and end_date to datetime
sessions_df['Start_Date'] = pd.to_datetime(sessions_df['Start_Date'], errors='coerce').dt.date
sessions_df['End_Date'] = pd.to_datetime(sessions_df['End_Date'], errors='coerce').dt.date
sessions_df.head()

   Congress  Start_Date    End_Date
0         1  1789-03-04  1791-03-03
1         2  1791-03-04  1793-03-03
2         3  1793-03-04  1795-03-03
3         4  1795-03-04  1797-03-03
4         5  1797-03-04  1799-03-03

In [6]:
# import data - bioguide profiles
bioguide_df = pd.read_csv("..\\data\\processed\\profiles_cleaned.csv")
bioguide_df.head()

  bioguide_id first_name    last_name  birth_date
0     A000002    Watkins       Abbitt  1908-05-21
1     A000009      James       Abdnor  1923-02-13
2     A000011      Homer        Abele  1916-11-21
3     A000014       Neil  Abercrombie  1938-06-26
4     A000016     Thomas    Abernethy  1903-05-16

In [8]:
# convert birth_date and death_dateto datetime
bioguide_df['birth_date'] = pd.to_datetime(bioguide_df['birth_date'], errors='coerce').dt.date
# bioguide_df['death_date'] = pd.to_datetime(bioguide_df['death_date'], errors='coerce').dt.date
bioguide_df.head()

  bioguide_id first_name    last_name  birth_date
0     A000002    Watkins       Abbitt  1908-05-21
1     A000009      James       Abdnor  1923-02-13
2     A000011      Homer        Abele  1916-11-21
3     A000014       Neil  Abercrombie  1938-06-26
4     A000016     Thomas    Abernethy  1903-05-16

In [9]:
# import data - congressional postings
postings_df = pd.read_csv("..\\data\\processed\\postings_cleaned.csv")
postings_df.head()

,bioguide_id,chamber,congress_number,region_type,region_code,party,start_date,end_date
0,A000002,Representative,86,State,VA,Democrat,1959-01-03,1961-01-02
1,A000016,Representative,86,State,MS,Democrat,1959-01-03,1961-01-02
2,A000024,Representative,86,State,IN,Republican,1959-01-03,1961-01-02
3,A000054,Representative,86,State,NJ,Democrat,1959-01-03,1961-01-02
4,A000062,Senator,86,State,VT,Republican,1959-01-03,1961-01-02

In [12]:
# convert date columns to datetime
postings_df['start_date'] = pd.to_datetime(postings_df['start_date'], errors='coerce').dt.date
postings_df['end_date'] = pd.to_datetime(postings_df['end_date'], errors='coerce').dt.date
# display first few rows
postings_df.head()

,bioguide_id,chamber,congress_number,region_type,region_code,party,start_date,end_date
0,A000002,Representative,86,State,VA,Democrat,1959-01-03,1961-01-02
1,A000016,Representative,86,State,MS,Democrat,1959-01-03,1961-01-02
2,A000024,Representative,86,State,IN,Republican,1959-01-03,1961-01-02
3,A000054,Representative,86,State,NJ,Democrat,1959-01-03,1961-01-02
4,A000062,Senator,86,State,VT,Republican,1959-01-03,1961-01-02

In [13]:
# from bioguide_df find the birthday for a specific congressperson
target_person = 'G000282'  # Example bioguide ID

birthday = bioguide_df.loc[bioguide_df['bioguide_id'] == target_person, 'birth_date']
print(f"Birthday of person with bioguide ID {target_person}: {birthday.values[0]}")

Birthday of person with bioguide ID G000282: 1926-03-16